updated README. various bug fixes

diff --git a/bin/osg-blast b/bin/osg-blast
--- a/bin/osg-blast
+++ b/bin/osg-blast
@@ -1,15 +1,35 @@
 #!/bin/bash
 
+if [ -d input ]; then
+    echo "input directory already exists. please remove before running"
+    exit 1
+fi
+
+#TODO - prevent job from running if there is another one already running?
+
+
 echo "Running Test"
 mkdir -p test-output
 osg-blast-test --config config.json --out stats.json --outdir test-output
+if [ $? -ne 0 ]; then
+    echo "test failed"
+    exit 1
+fi
 
 echo "Splitting input file"
 mkdir -p input
 osg-blast-split --config config.json --stats stats.json --outdir input
+if [ $? -ne 0 ]; then
+    echo "split failed"
+    exit 1
+fi
 
 echo "Generating condor dag"
-osg-blast-gendag --config config.json --input input
+osg-blast-gendag --config config.json --input input --outdir output
+if [ $? -ne 0 ]; then
+    echo "failed to generate condor dag"
+    exit 1
+fi
 
 echo "Submitting dag"
 mkdir -p log
@@ -17,4 +37,21 @@ mkdir -p output
 condor_submit_dag blast.dag
 
 echo "waiting for workflow to finish"
+sleep 10 #is 10 seconds enough?
 condor_wait blast.dag.dagman.log
+if [ $? -ne 0 ]; then
+    echo "workflow failed"
+    exit 1
+fi
+
+echo "checking for output"
+osg-blast-checkoutput --config config.json --input input --outdir output
+if [ $? -ne 0 ]; then
+    echo "incomplete output.. workflow failed with pertial output"
+    exit 1
+fi
+
+echo "TODO - run merge step"
+
+
+
diff --git a/bin/osg-blast-merge6 b/bin/osg-blast-merge6
--- a/bin/osg-blast-merge6
+++ b/bin/osg-blast-merge6
@@ -1,20 +1,38 @@
 #!/bin/bash
 
 #this script merged output generated with -outfmt 6
+# sample output file name: nr.09.q.613
 
-echo "merging dbparts"
+function globexists {
+  test -e "$1" -o -L "$1"
+}
+
 query_block=0
-while [ -f output.qb_$query_block.db_0 ]
-do
-    echo "merging query block $query_block"
-    ls output.qb_$query_block.*
-    sort output.qb_$query_block.* > merged.qb_$query_block
-    query_block=$((query_block+1))
+#while [ -f output.qb_$query_block.db_0 ]
+while true; do
+    #[ $(find . -name '*.q.$query_block') ]
+    if test -n "$(shopt -s nullglob; echo *.q.$query_block.gz)"
+    then
+        echo "unzip query block $query_block"
+        ls *.q.$query_block.gz
+        gunzip *.q.$query_block.gz
+
+        echo "sorting query block $query_block"
+        sort *.q.$query_block | gzip -c > merged.q.$query_block.gz
+
+        echo "gziping back query block $query_block"
+        gzip *.q.$query_block
+        query_block=$((query_block+1))
+    else
+        echo "merging complete"
+        exit 0
+    fi
 done
 
-echo "merging query blocks"
-#sort merged.qb_* > merged
-cat merged.qb_* > merged
+echo "can't concatenate.."
+exit 1
+#echo "concatenating query blocks"
+#cat merged.q.* > merged
 
-echo "removing temp files"
-rm merged.qb_*
+#echo "removing temp files"
+#rm merged.q.*
